export default {
  '1': 'Heh-GLUGK!',
  '2': 'BreeeEEEUUuugh.',
  '3': 'Blulg.',
  '4': 'Excuse me I just… HYUGHGUCK.',
  '5': 'I just, one second I GLOOUGH.',
  '6': 'UH-BAAH! Whoa what was that? Anyway…',
  '7': 'Hug-geh!',
  '8': 'Eh-GUH!',
  '9': 'GYEECK-whoops.',
  '10': 'FLLLEOOOUCK.',
  '11': 'ERRAGGG.',
  '12': 'Uh-RRROAK.',
  '13': 'Wait just WEEEORK-ugh.',
  '14': 'Oh I GLEUUUGH.',
  '15': 'Hick-CHAAAUGH.',
  '16': 'Sorry I WOOOAGH sorry.',
  '17': 'BLEEEG.',
  '18': 'I can’t CROOOOWK.',
  '19': 'Her-AOOOKE.',
  '20': 'BYOOOUK.',
  '21': 'I just JYOO-ORK.',
  '22': 'GUH-RUKK.',
  '23': 'BREPP.',
  '24': 'GRUK GRUK GRUK.',
  '25': 'Oh waiEEEEEYUUUG.',
  '26': 'FROHPE!',
  '27': 'FUH-FLOOOKE.',
  '28': 'Well WYUUURG.',
  '29': 'FRRRRRUGCK. Um, I FRRRUGHMM, meh.',
  '30': 'Bruh-bruuuUUUUgh!',
  '31': 'GRUUUOAK!',
  '32': 'Let’s justRROOOAK.',
  '33': 'BRRRAYYYT.',
  '34': 'BOOO-RUGG.',
  '35': 'Let’s HROOUCK!',
  '36': 'UGH-GUG-GRUCK.',
  '37': 'I WOOORF, I… oh my.',
  '38': 'BAYROOOOK.',
  '39': 'I caAAAYUUUCK.',
  '40': 'Wait WAOOOORF.',
  '41': 'Hnngnngh-GLORRG!',
  '42': 'Hold OOOONNNOOOARK.',
  '43': 'Buh-buh-bYOOAAWN.',
  '44': 'Uh-guh-GREK oh no.',
  '45': 'WHEE-YAAAAHP.',
  '46': 'Ahem. So shOOORP whoa uh, ok.',
  '47': 'BLORF.',
  '48': 'FEGH.',
  '49': 'HYOOOAUUGH.',
  '50': 'BROOORMP.',
  '51': 'FLEEERAAUUUGH.',
  '52': 'FleaBOARG.',
  '53': 'TerMEROROR.',
  '54': 'Oh OOOARGERG.',
  '55': 'BLOARK.',
  '56': 'KR-OOONK.',
  '57': 'GRAAAAYNG.',
  '58': 'HYUKUH-uh, oh god.',
  '59': 'HRRRNG oh.',
  '60': 'UCK.',
  '61': 'RAAAYMS.',
  '62': 'GERUGGGH.',
  '63': 'CORM.',
  '64': 'FLEXGHM. Ahem.',
  '65': 'FWOP. Whoa.',
  '66': 'REEAAYROM.',
  '67': 'Ugh. GLAAAUGGH.',
  '68': '*lips closed, jaw wide* OOOROOO.',
  '69': '*smack lips* Hrm-ORRRRM, welp yes.',
  '70': 'FWEP.',
  '71': 'TORQUE.',
  '72': 'I-IPEROUSE oh ohs.',
  '73': 'ERRRITE! OH!',
  '74': 'GROMM!',
  '75': 'CROOOOAD.',
  '76': 'FW-AHM.',
  '77': 'BROOO-EEP.',
  '78': 'KWAKOL.',
  '79': 'MELK. Oh that wasn’t, oh.',
  '80': 'CLOP!',
  '81': 'MAYP.',
  '82': 'GWOPUP.',
  '83': 'Hrm. HMOP oh, shoot.',
  '84': 'CAAAYPE.',
  '85': 'Ehck.',
  '86': 'FuuccgggECH-UGH.',
  '87': 'CROOT.',
  '88': 'BOMP.',
  '89': 'PLORRP.',
  '90': 'FUUUUG!',
  '91': 'TWEP!',
  '92': 'FLECCCH!',
  '93': 'OoohKWOMP oh.',
  '94': 'Beck. What?',
  '95': 'POOORK.',
  '96': 'BOMPUCK.',
  '97': '*in the quietest of whispers* blfff.',
  '98': 'FLAAANGK.',
  '99': 'CLEEEAAAGH.',
  '100': 'Woof, excus-MEUUGHUGH!'
}
